language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t judsondouglas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true judsondouglas/docker-react npm run test